# Generated by Django 3.1.3 on 2020-12-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=500)),
                ('result', models.FloatField()),
                ('responseTime', models.IntegerField()),
                ('isCalculated', models.BooleanField()),
                ('createdDate', models.DateTimeField()),
                ('executionDate', models.DateTimeField()),
            ],
        ),
    ]
